### ISSUE TITLE
Métricas de teste no FrontEnd

### ISSUE THREAD

**Issue by RuanMoura** [fga-eps-mds/2022-2-Alectrion-DOC#100]
**Descrever o bug**
O Sonar não está reconhecendo os arquivos de testes no front end, então as métricas de cobertura necessárias para as análises acabam não sendo coletadas.
**Como reproduzir o bug**
Passos para ocorrer o bug:
1. Executando o workflow SonarCloud

**Comportamento Esperado**
Espera que as métricas de Tests, Test errors, Test failures e Test execution time. Metricas estas definidas no nosso plano de qualidade em [plano-qualidade.md](https://github.com/fga-eps-mds/2022-2-Alectrion-DOC/blob/main/docs/Planejamento/plano-qualidade.md).

**Comment by ErickGiffoni** [comment]
CI falha porque os testes do front estão falhando
