### ISSUE TITLE
US 07: Cadastro de ordem de serviço

### ISSUE THREAD

**Issue by ErickGiffoni** [fga-eps-mds/2022-2-Alectrion-DOC#16]
# US 07: Cadastro de ordem de serviço

**Descrição**
Eu como ***funcionário do DSTI*** gostaria de ***realizar o cadastro e edição ordem de serviço*** para ***manter o controle dos consertos (suporte) que um equipamento de informática teve***.

[Figma](https://www.figma.com/file/UaUTq18rw4VxKExnPCp5N5/Alectrion-(Copy)?node-id=69%3A2&t=5dbmtxETvbOgiEsI-0)

**Tarefas**

- [x] [FRONT] Tela de consulta de ordem de serviço
- [x] [FRONT] Tela de cadastro de ordem de serviço
- [x] [FRONT] Tela da atualizar informações da ordem de serviço
- [x] [FRONT] Viabilizar a movimentação (BAIXAR ou RESERVA TÉCNICA) do equipamento dentro da ordem de serviço
- [x] [BACK] Endpoint de cadastro de ordem de serviço
- [ ] [BACK] Endpoint para ler as informações das ordens de serviço
- [x] [BACK] Endpoint para alterar o status da ordem de serviço, em caso de status concluído é preciso registrar as demais informações da manutenção 

**Critérios de Aceitação**

- [x] Cadastrar Ordem de Serviço, inserindo o Tombamento do equipamento (assim, a aplicação irá trazer todos os dados e especificações do equipamento, inclusive a sua Lotação;
- [x] Deverá registrar automaticamente a DATA de entrada do equipamento;
- [x] Na O.S deverá constar automaticamente o login do servidor da DSTI que registrou a O.S;
- [x] Deverá gerar um numero de O.S, que deverá ser vinculada ao status do equipamento;
- [x] Ao dar entrada na Oficina, o status do equipamento deverá ser mudado automaticamente para Em Manutenção - O.S nº xxxx;
- [x] A O.S deverá ter 3 três status: Em manutenção, Para Garantia e Concluído;
- [x] Ao concluir a O.S, deverá haver um campo (não obrigatório) para informar qual ou quais técnicos realizaram a manutenção do equipamento;
- [x] No momento do cadastro da O.S deverá ser informado dados da pessoa que está entregando: **NOME, Nº da FUNCIONAL**;
- [ ] No momento da devolução do equipamento deverá ser informado dados da pessoa que está recebendo: **DATA, NOME, Nº da FUNCIONAL**;
- [x] Deverá haver um campo para descrever o problema do equipamento a ser realizado a manutenção, bem como outras informações pertinentes;
- [ ] Na própria O.S, deverá haver a possibilidade de movimentar o equipamento para BAIXAR ou RESERVA TÉCNICA.

**Comment by ErickGiffoni** [comment]
@CarlosEduardoMendesdeMesquita e @mathonaut 
Façam a edição da US conforme o template ASAP
Assim que fizerem isso, mandem o link da US pelo Discord, marcando os PO (pessoal da Polícia) e peçam que coloquem os critérios de aceitação aqui.

**Comment by guilhermepupak** [comment]
Critérios de Aceitação:

- Cadastrar Ordem de Serviço, inserindo o Tombamento do equipamento (assim, a aplicação irá trazer todos os dados e especificações do equipamento, inclusive a sua Lotação;
- Deverá registrar automaticamente a DATA de entrada do equipamento;
- Na O.S deverá constar automaticamente o login do servidor da DSTI que registrou a O.S;
- Deverá gerar um numero de O.S, que deverá ser vinculada ao status do equipamento;
- Ao dar entrada na Oficina, o **status do equipamento** deverá ser mudado automaticamente para **Em Manutenção - O.S nº xxxx**
- A **O.S deverá ter 3 três STATUS**: **Em manutenção**; **Para Garantia**; **Concluído**.
- Ao concluir a O.S, deverá haver um campo (não obrigatório) para informar qual ou quais técnicos realizaram a manutenção do equipamento;
- No momento do **cadastro da O.S** deverá ser informado dados da pessoa que está entregando: NOME, Nº da FUNCIONAL;
-  No momento da **devolução do equipamento** deverá ser informado dados da pessoa que está recebendo: DATA, NOME, Nº da FUNCIONAL;
- Deverá haver um campo para descrever o problema do equipamento a ser realizado a manutenção, bem como outras informações pertinentes.
- Na própria O.S, deverá haver a possibilidade de movimentar o equipamento para BAIXAR ou RESERVA TÉCNICA.

**Comment by ErickGiffoni** [comment]
Como está o andamento dessa US ? Quais são os _Pull Requests_ envolvidos ?
Já teve revisão nos PRs ? O que está faltando fazer p/ finalizar a US ?
Existe algum impedimento ?
@CarlosEduardoMendesdeMesquita @mathonaut

**Comment by CarlosEduardoMendesdeMesquita** [comment]
O andamento está atrasado, tivemos impedimentos por não entender muito bem o que já tem e o que não tem para incrementar e matheus possui três provas essa semana, então não tivemos como nos reunir, mas pelo que consegui ver, falta implementar apenas a tela de atualizar informações e criar a movimentação e implementar cadastro por tombamento.

**Comment by ErickGiffoni** [comment]
Ok, @CarlosEduardoMendesdeMesquita, obrigado.
Prossigam com o Desenvolvimento, mesmo que não consigam se reunir para fazer juntos, porque isso não pode ser um impedimento.
Se precisar de ajuda, voltamos a dizer, procure seus colegas (EPS e MDS), não deixe pra depois.
