### ISSUE TITLE
US 12: Geração de termos

### ISSUE THREAD

**Issue by SamButers** [fga-eps-mds/2022-2-Alectrion-DOC#37]
# US 12: Geração de termos

**Descrição**
Eu como ***persona*** gostaria de ***gerar um termo*** para ***imprimí-lo***.

**Tarefas**

- [ ] Gera termo
- [ ] Abre termo em nova aba para visualização

**Critérios de Aceitação**

- [ ] Deve ser possível realizar a impressão do termo

**Comment by SamButers** [comment]
Os termos e demais documentos em PDF devem ser visualizados em uma nova aba, não baixados diretamente.

**Comment by AlineLermen** [comment]
# Roteiro para testes do usuário

História(s) a ser(em) testada(s): **US 01** (#7), **US 02** (#8), **US 03** (#9), **US 04** (#10), **US 05** (#12), **US 06** (#13), **US 07** (#16), **US 11** (#36) e **US 12** (#37)

Testadores: Guilherme e Dirlei

### Passos para os testes

Para cada passo executado abaixo, **marque a caixa de seleção** correspondente para indicar a correta execução do que foi pedido.

**Obs.:** Caso seja necessário indicar mudanças ou não conformidade aos critérios de aceitação da(s) respectiva(s) história(s), responda ao presente roteiro com um comentário, marcando o "@" dos _assignees_ (MDS) e pelo menos um "@" dos EPS.

1. Acesse a aplicação em: https://alectrion-2022.herokuapp.com/login
- [ ] ok

2. Faça _login_ com as credenciais:
  * Username: admin
  * Senha: admin1234
- [ ] ok

3. Crie um novo usuário utilizando os dados que desejar. ATENÇÃO: NÃO dê perfil de administrador para o novo usuário !
- [ ] ok

4. Faça a edição de algum dado desse novo usuário criado
- [ ] ok

4.1. Edite a senha do novo usuário criado (e lembre-se dessa senha, você vai precisar dela mais adiante)
- [ ] ok

5. Faça _logout_ da aplicação. Em seguida faça _login_ com as credenciais do novo usuário
- [ ] ok

5.1. Ao fazer o _login_, o sistema pediu a você (novo usuário) a modificação imediata da sua senha de acesso, já que é a primeira vez que você faz o _login_ (US 5)
- [ ] ok

6. Navegue na interface e veja se as ações permitidas desse usuário estão de acordo com o perfil dele
- [ ] ok

6.1. Tente editar sua própria senha, desse novo usuário que você fez _login_. Esse passo DEVE falhar
- [ ] ok, falhou, porque somente o usuário com perfil de administrador pode alterar senhas.

7. Faça _logout_ da aplicação. Em seguida faça _login_ com as credenciais do passo 2
- [ ] ok

8. Exclua o novo usuário que fora criado anteriormente
- [ ] ok

9. Navegue para o cadastro de equipamentos
- [ ] ok

10. Na tela de cadastro, observe se/que:
- [ ] O campo "Unidade" não deve aparecer
- [ ] O campo "Situação" (anteriormente A.K.A "Status") tem as opções: "Ativo; Ativo empréstimo; Em manutenção; Baixado; Reserva técnica"

11. Cadastre o equipamento
- [ ] ok

12. Verifique se o equipamento foi cadastrado e se:
- [ ] O campo "Unidade" tem como valor padrão o DSTI
- [ ] A situação do equipamento está como "reserva técnica"

13. Faça _logout_, depois _login_ com credenciais de algum usuário que NÃO seja perfil de administrador. Se precisar, crie um usuário com outro perfil. Depois verifique que, na página de equipamentos, não é possível excluir um equipamento se o usuário não for administrador
- [ ] ok

⚠️**Continue na aplicação com perfil que não seja administrador**⚠️

14. Volte ao cadastro de equipamentos. Verifique que, para os equipamentos como "CPU; MONITOR; ESTABILIZADOR e NOBREAK", as seguintes informações adicionais aparecem (cada qual pertinente ao equipamento em questão):
- [ ] Memória RAM (referente a CPU)
- [ ] Armazenamento (referente a CPU)
- [ ] Tipo de armazenamento (referente a CPU)
- [ ] Processador (referente a CPU)
- [ ] Tipo do monitor (referente a monitor)
- [ ] Tamanho do monitor (referente a monitor)
- [ ] Potência (referente a NoBreak)

14.1. Cadastre um equipamento diferente dos passos 10 e 11 e verifique que foi cadastrado com sucesso
- [ ] ok

15. Faça consultas por um equipamento utilizando diferentes informações como objeto de cada consulta (ex.: uma consulta por "Modelo", outra por "Marca" etc)
- [ ] ok

16. Existe o MENU COM FILTRO, para uma melhor eficiência dessas consultas ?
- [ ] ok

17. Navegue para o cadastro de ordens de serviço
- [ ] ok

17.1. Informe o número de tombamento referente ao equipamento e verifique que a aplicação irá trazer todos os dados e especificações do equipamento, inclusive a sua Lotação
- [ ] ok

17.2. Verifique as 3 possibilidades para status da ordem de serviço: Em manutenção, Para Garantia e Concluído;
- [ ] ok

17.3. No momento do cadastro da O.S deverá ser informado dados da pessoa que está entregando: NOME, Nº da FUNCIONAL
- [ ] ok

17.4. Deverá haver um campo para descrever o problema do equipamento a ser realizado a manutenção, bem como outras informações pertinentes;
- [ ] ok

17.5. Na própria O.S, deverá haver a possibilidade de movimentar o equipamento para BAIXAR ou RESERVA TÉCNICA
- [ ] ok

18. Cadastre uma ordem de serviço (OS).
- [ ] ok

19. Verifique, para a OS cadastrada, que:
- [ ] A DATA de entrada do equipamento foi automaticamente registrada
- [ ] Consta automaticamente o login do servidor da DSTI que registrou a O.S
- [ ] Há um numero de O.S, que deverá ser vinculada ao status do equipamento (é provável que vc precise navegar para a tela de equipamentos)
- [ ] Ao dar entrada na Oficina, o status do equipamento deverá ser mudado automaticamente para Em Manutenção - O.S nº xxxx

20. Faça a conclusão da OS e verifique que:
- [ ] Há haver um campo (não obrigatório) para informar qual ou quais técnicos realizaram a manutenção do equipamento
- [ ] No momento da devolução do equipamento deverá ser informado dados da pessoa que está recebendo: DATA, NOME, Nº da FUNCIONAL

21. Existe uma tela para consulta das OS
- [ ] ok

22. Existe tela para atualizar informações de uma ordem de serviço
- [ ] ok

23. Navegue para a tela de equipamentos. Caso haja um equipamento já cadastrado, utilize-o para o passo seguinte. Caso não, crie um novo equipamento qualquer.
- [ ] ok

24. Selecione o(s) equipamento(s) que farão parte de uma movimentação. Para selecioná-los, clique no último botão, que contém 2 setas. Depois, clique no botão "gerar movimentação" e preencha as informações da mesma.
- [ ] ok

25. Navegue para a tela de movimentações, verifique se a nova movimentação está cadastrada, e se seus dados estão de acordo
- [ ] ok

26. Volte para a tela de equipamentos, e verifique se o campo "situação" do equipamento foi atualizado corretamente de acordo com a movimentação gerada.
- [ ] ok

27. Gere 2 ou 3 movimentações. Clique no campo "filtro" e teste algumas buscas por campos diferentes
- [ ] ok

28. Para obter o termo de uma movimentação, clique no ícone de "pdf" da movimentação que desejar e preencha os dados de órgão e data de entrega e confirme.
- [ ] ok

29. O termo da movimentação escolhida pode ser visualizado, com seus dados corretos
- [ ] ok

## Testes finalizados... e agora ?

* Entre nas _issues_ referentes às histórias testadas. Na descrição da US, onde há os **Critérios de Aceitação**, marque todas as caixas de seleção para indicar que os critérios foram atendidos. Ou, caso contrário, faça um comentário para explicar o que está errado ou o que faltou
* Avise a equipe (pelo canal do Discord) que esse roteiro foi seguido, executado e finalizado.

## Obrigado!

Qualquer dúvida ou sugestão é só falar conosco pelo Discord.
