### ISSUE TITLE
US 01: Cadastro de usuário

### ISSUE THREAD

**Issue by ErickGiffoni** [fga-eps-mds/2022-2-Alectrion-DOC#7]
# US01: Cadastro de usuário

**Descrição**
Eu como ***funcionário do DSTI*** gostaria de ***realizar o cadastro de usuários*** para ***acessar a aplicação***.

**Tarefas**

- [x] Cadastro de usuário
- [x] Edição de usuário
- [x] Exclusão de usuário
- [x] Escrever testes

**Critérios de Aceitação**

- [x] O usuário poderá logar na Aplicação tanto pelo Nome de Usuário ou pelo E-mail;
- [x] O cargo do usuário é apenas um informativo do usuário, não irá determinar nenhum privilégio dentro da Aplicação (Coordenador, Chefe, Gerente, Escrivão, Agente, Delegado.... etc);
- [x] O PERFIL do usuário irá determinar seu privilégio dentro da Aplicação, podendo ser:
- Administrador (Consultar ; Cadastrar; Editar ; Excluir);
- Gerente (Consultar ; Cadastrar; Editar);
- Básico Consultar ; Cadastrar);
- Consulta (apenas Consultar)

**Comment by ErickGiffoni** [comment]
Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Alectrions-2022-2-Zenhub-638111f7e221121525eab59b/issues/fga-eps-mds/2022-2-Alectrion-DOC/7?planning-poker) with Zenhub @RuanMoura

**Comment by ErickGiffoni** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Alectrions-2022-2-Zenhub-638111f7e221121525eab59b/issues/fga-eps-mds/2022-2-Alectrion-DOC/7?planning-poker) with Zenhub @AlineLermen @AlvaroLeles @JoaoVitorFarias

**Comment by Galaxia1000** [comment]
3

**Comment by guilhermepupak** [comment]
**Critérios de aceitação:**
Deve-se ser possível cadastrar usuário com todas essas opções conforme imagem anexa.

1. O usuário poderá logar na Aplicação tanto pelo **Nome de Usuário** ou pelo **E-mail**;
2. O cargo do usuário é apenas um informativo do usuário, não irá determinar nenhum privilégio dentro da Aplicação (Coordenador, Chefe, Gerente, Escrivão, Agente, Delegado.... etc);
3. O **PERFIL** do usuário irá determinar seu privilégio dentro da Aplicação, podendo ser:
- Administrador (Consultar ; Cadastrar; Editar ; Excluir);
- Gerente (Consultar ; Cadastrar; Editar);
- Básico Consultar ; Cadastrar);
- Consulta (apenas Consultar).

Obs.: Acredito que o layout possa ser melhorado, mas prefiro focar nas funcionalidades primeiro, e só depois na aparência.

![image](https://user-images.githubusercontent.com/109108065/205361258-5b22cc92-b923-44d3-8d90-1e7f3f5708d4.png)

**Comment by ErickGiffoni** [comment]
# Roteiro para testes do usuário

História(s) a ser(em) testada(s): **US 01** (#7), **US 02** (#8) e **US 03** (#9)

Testadores: Guilherme e Dirlei

### Passos para os testes

Para cada passo executado abaixo, **marque a caixa de seleção** correspondente para indicar a correta execução do que foi pedido.

**Obs.:** Caso seja necessário indicar mudanças ou não conformidade aos critérios de aceitação da(s) respectiva(s) história(s), responda ao presente roteiro com um comentário, marcando o "@" dos _assignees_ (MDS) e pelo menos um "@" dos EPS.

1. Acesse a aplicação em: https://alectrion-2022.herokuapp.com/login
- [ ] ok

2. Faça _login_ com as credenciais:
  * Username: admin
  * Senha: admin1234
- [ ] ok

3. Crie um novo usuário utilizando os dados que desejar
- [ ] ok

4. Faça a edição de algum dado desse novo usuário criado
- [ ] ok

5. Faça _logout_ da aplicação. Em seguida faça _login_ com as credenciais do novo usuário
- [ ] ok

6. Navegue na interface e veja se as ações permitidas desse usuário estão de acordo com o perfil dele
- [ ] ok

7. Faça _logout_ da aplicação. Em seguida faça _login_ com as credenciais do passo 2
- [ ] ok

8. Exclua o novo usuário que fora criado anteriormente
- [ ] ok

## Testes finalizados... e agora ?

* Entre nas _issues_ referentes às histórias testadas. Na descrição da US, onde há os **Critérios de Aceitação**, marque todas as caixas de seleção para indicar que os critérios foram atendidos. Ou, caso contrário, faça um comentário para explicar o que está errado ou o que faltou
* Avise a equipe (pelo canal do Discord) que esse roteiro foi seguido, executado e finalizado.

## Obrigado !

Qualquer dúvida ou sugestão é só falar conosco pelo Discord.

**Comment by ErickGiffoni** [comment]
Como está o andamento dessa US ? Quais são os _Pull Requests_ envolvidos ?
Já teve revisão nos PRs ? O que está faltando fazer p/ finalizar a US ?
Existe algum impedimento ?
@pedrogot11 @mathonaut

**Comment by mathonaut** [comment]
US finalizada. Já foram dados os _merges_ dos _Pull Requests_ na _branch dev_ nos repositórios de _Front_ e _UserApi_.

**Comment by guilhermepupak** [comment]
> # Roteiro para testes do usuário
> 
> História(s) a ser(em) testada(s): **US 01** (#7), **US 02** (#8) e **US 03** (#9)
> 
> Testadores: Guilherme e Dirlei
> ### Passos para os testes
> 
> Para cada passo executado abaixo, **marque a caixa de seleção** correspondente para indicar a correta execução do que foi pedido.
> 
> **Obs.:** Caso seja necessário indicar mudanças ou não conformidade aos critérios de aceitação da(s) respectiva(s) história(s), responda ao presente roteiro com um comentário, marcando o "@" dos _assignees_ (MDS) e pelo menos um "@" dos EPS.
> 
>     1. Acesse a aplicação em: https://alectrion-2022.herokuapp.com/login
> 
> 
>     * [ok]  ok
> 
> 
>     2. Faça _login_ com as credenciais:
> 
> 
>     * Username: admin
> 
>     * Senha: admin1234
> 
> 
>     * [ok]  ok
> 
> 
>     3. Crie um novo usuário utilizando os dados que desejar
> 
> 
>     * [ok]  ok
> 
> 
>     4. Faça a edição de algum dado desse novo usuário criado
> 
> 
>     * [ok]  ok
> 
> 
>     5. Faça _logout_ da aplicação. Em seguida faça _login_ com as credenciais do novo usuário
> 
> 
>     * [ok]  ok
> 
> 
>     6. Navegue na interface e veja se as ações permitidas desse usuário estão de acordo com o perfil dele
> 
> 
>     * [RESSALTA]  ok
>
> Obs. Ressalva ao ítem "6": O usuário criado com perfil de GERENTE, pode editar outros usuários (ok). Contudo, esse "Gerente" consegue mudar o perfil de outros usuários, bem como também o próprio perfil, para ADMINISTRADOR. Na verdade não poderia, uma vez que ele não pode possuir Atribuição de Administrador na aplicação, mas somente de Gerente. Acredito que a escolha dos Perfis de usuário deva ser somente uma prerrogativa do ADMINISTRADOR. Ou, o GERENTE até poderia criar um usuário, mas com opção de escolhe de perfil de usuário menor que o dele, ou seja, BÁSICO ou CONSULTA.
> 
>     7. Faça _logout_ da aplicação. Em seguida faça _login_ com as credenciais do passo 2
> 
> 
>     * [ok]  ok
> 
> 
>     8. Exclua o novo usuário que fora criado anteriormente
> 
> 
>     * [ok]  ok
> 
> 
> ## Testes finalizados... e agora ?
> 
>     * Entre nas _issues_ referentes às histórias testadas. Na descrição da US, onde há os **Critérios de Aceitação**, marque todas as caixas de seleção para indicar que os critérios foram atendidos. Ou, caso contrário, faça um comentário para explicar o que está errado ou o que faltou
> 
>     * Avise a equipe (pelo canal do Discord) que esse roteiro foi seguido, executado e finalizado.
> 
> 
> ## Obrigado !
> 
> Qualquer dúvida ou sugestão é só falar conosco pelo Discord.

**Comment by ErickGiffoni** [comment]
Entregue
