### ISSUE TITLE
US 02: Sessão de usuário

### ISSUE THREAD

**Issue by ErickGiffoni** [fga-eps-mds/2022-2-Alectrion-DOC#8]
# US \<id\>: \<sintese da US \>

**Descrição**
Eu como ***persona*** gostaria de ***realizar*** para ***alcancar um objetivo***.

Exemplo: Eu como usuário gostaria de cadastrar um equipamento para registrar meu inventário.

**Tarefas**

- [x] Login de usuário (com interface)
  - [x] Gerar a sessão e salvar (no browser e/ou no back... cookies ? local storage ?)
- [x] Logout

**Critérios de Aceitação**

- [x] Botão de logout (Redireciona o usuário para a tela de login)
- [x] Ter Feedback de erros

**Comment by ErickGiffoni** [comment]
Para discutir: Salvar a sessão após fechamento do browser ? E quando o usuário ficar X minutos em inatividade, qual o comportamento esperado do sistema ?

**Comment by ErickGiffoni** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Alectrions-2022-2-Zenhub-638111f7e221121525eab59b/issues/fga-eps-mds/2022-2-Alectrion-DOC/8?planning-poker) with Zenhub @AlineLermen @AlvaroLeles @JoaoVitorFarias @Galaxia1000 @mathonaut @Dridr1 @SamButers @RuanMoura

**Comment by guilhermepupak** [comment]
**Critérios de aceitação**
Cada usuário logado deverá ter um tempo de inatividade estabelecido, caso exceda esse tempo, a aplicação irá deslogar automaticamente. Acredito que o tempo limita poderá ser de 20 minutos. Nesse caso, a aplicação deverá me informar, no canto superior direito, 1 minuto antes, de que o usuário será desconectado por inatividade.

Caso fechar o browser (acidentalmente) a aplicação deverá informar que existe usuário conectado, e perguntar se deseja deslogar.

Deverá haver botão para realizar o logout da aplicação; Aparecer nome do usuário conectado e perfil do usuário, no canto superior direito, conforme imagem:

![image](https://user-images.githubusercontent.com/109108065/205365803-4c858be5-9d06-493b-aa27-f3d26395ffd5.png)

**Comment by ErickGiffoni** [comment]
Como está o andamento dessa US ? Quais são os _Pull Requests_ envolvidos ?
Já teve revisão nos PRs ? O que está faltando fazer p/ finalizar a US ?
Existe algum impedimento ?
@pedrogot11 @mathonaut

**Comment by ErickGiffoni** [comment]
Entregue
