### ISSUE TITLE
Adicionar bot no telegram

### ISSUE THREAD

**Issue by AlineLermen** [fga-eps-mds/2022-2-Alectrion-DOC#82]
Uma issue deve ser criada com a finalidade de descrever:
 - Uma tarefa do projeto

**Descrição**
Adicionar bot no telegram para dar um alerta nos horários das reuniões

**Tarefas :** 
- [x] Procurar um bot
- [x] Adicionar/configurar o bot

**Comment by SamButers** [comment]
O bot está atualmente programado para avisar acerca de dailies nas terças e quintas às 15:50.
Isso está atualmente em teste.

**Comment by SamButers** [comment]
Testado e funcionando.
