### ISSUE TITLE
US 03: Visualizar perfil de usuário

### ISSUE THREAD

**Issue by ErickGiffoni** [fga-eps-mds/2022-2-Alectrion-DOC#9]
# US 03: Visualizar perfil de usuário

**Descrição**
Eu como ***ADMINISTRADOR*** gostaria de ***ter acesso aos perfis de usuário*** para ***visualizar e realizar alterações nos mesmos*** .

Exemplo: Eu, como ADMINISTRADOR, quero realizar alterações de permissão de um determinado usuário, para que ele tenha acesso não somente a consultas, mas também a cadastro de equipamentos.

**Tarefas**

- [x] Usuário Administrador criado e com as devidas permissões
- Botão excluir e editar devem aparecer
- [x] Usuário Gerente criado e com as devidas permissões
- Aparece o botão de excluir - OS e Equip.
- [x] Usuário Básico criado e com as devidas permissões
- Aparece o botão de editar e excluir - OS e Equip.
- [x] Usuário Consulta criado e com as devidas permissões
-  Atualmente consegue realizar cadastro e aparece o botão de editar e excluir - OS e Equip.

**Critérios de Aceitação**

- [x] Precisa haver os 4 tipos de usuários (Administrador, Gerente, Básico, Consulta);
- [x] Somente usuários administradores podem visualizar informações de outros usuários;

**Comment by ErickGiffoni** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Alectrions-2022-2-Zenhub-638111f7e221121525eab59b/issues/fga-eps-mds/2022-2-Alectrion-DOC/9?planning-poker) with Zenhub @AlineLermen @AlvaroLeles @Dridr1 @Galaxia1000 @JoaoVitorFarias @mathonaut @RuanMoura @SamButers

**Comment by guilhermepupak** [comment]
**Critérios de Aceitação**

Segue abaixo os perfil de usuários e seus privilégios.
- Administrador (Consultar ; Cadastrar; Editar ; Excluir);
- Gerente (Consultar ; Cadastrar; Editar);
- Básico Consultar ; Cadastrar);
- Consulta (apenas Consultar).

Obs.: Somente usuários administradores podem visualizar informações de outros usuários

**Comment by ErickGiffoni** [comment]
Como está o andamento dessa US ? Quais são os _Pull Requests_ envolvidos ?
Já teve revisão nos PRs ? O que está faltando fazer p/ finalizar a US ?
Existe algum impedimento ?
@Yagoas @MatsFidelis

**Comment by MatsFidelis** [comment]
A US 03 Está finalizada, o pull request referente a esta US é o [#3](https://github.com/fga-eps-mds/2022-2-Alectrion-FrontEnd/pull/3), sendo o mesmo já revisado e feito o Merge.
@ErickGiffoni

**Comment by ErickGiffoni** [comment]
> A US 03 Está finalizada, o pull request referente a esta US é o [#3](https://github.com/fga-eps-mds/2022-2-Alectrion-FrontEnd/pull/3), sendo o mesmo já revisado e feito o Merge.
> @ErickGiffoni

Ok, @MatsFidelis , muito Obrigado. Foi só esse o PR mesmo sobre essa US ? Não tem mais nenhum ?

**Comment by MatsFidelis** [comment]
@ErickGiffoni isso, somente este PR referente a essa US.
